name: ci
on:
  pull_request:
    branches:
      - v11-next-step-1


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  step-one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            */**/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Run ci checks
        run: yarn ci-check
      - name: Build project
        run: yarn build
    #   - name: Run tests
    #     run: yarn test
